version: 2.1
jobs:
    trial:
      docker:
            - image: cimg/node:18.2.0
      parallelism: 1
      steps:
        - run:
            name: "trial"
            command: lscpu

workflows:
    version: 2.1
    build:
        jobs:
        - trial
